name: Fossa

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run Fossa License Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Fossa License Check
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: ./tooling/fossa/fossa.sh
